// Algoritmo menu
	
// 	Escribir "Hola profe, cómo te llamás?"
	
// 	Leer nombre_profesor
	
// 	Escribir "Bienvenido/a ", nombre_profesor, "! por favor eligí una opción del menú y escribí el numero correspondiente:"
	
// 	Definir numero_seleccionado Como Entero
	
// 	Definir flag_salida Como Logico
// 	flag_salida <- Falso
	
// 	Repetir
		
// 		opcion_elegida <- menu_y_socilitud_valor()
		
// 		Segun opcion_elegida Hacer
// 			1:
// 				ver_notas()
// 			2:
// 				nuevo_alumno()
// 			3:
// 				ver_promedio_general()
// 			4:
// 				Escribir "Bye Bye!"
// 				flag_salida <- Verdadero
				
// 			De Otro Modo:
// 				Escribir "Debes seleccionar una opción válida"
// 		Fin Segun
		
// 	Hasta Que flag_salida
	
// FinAlgoritmo














// Funcion numero_seleccionado <- menu_y_socilitud_valor
	
	
// 	Escribir "1: Ver notas de alumno"
// 	Escribir "2: Ingresar nuevo alumno"
// 	Escribir "3: Ver promedio del curso"
// 	Escribir "4: Salir"
	
// 	Leer numero_seleccionado
	
// FinFuncion

// Funcion ver_notas
// 	Escribir "Esta función aún está en construcción"
// FinFuncion

// Funcion nuevo_alumno
// 	Escribir "Decime el nombre del Alumno"
// 	Leer nombre_alumno
	
// 	Dimension notas[3]
	
// 	Para i <- 1 Hasta 3 Hacer
// 		Escribir "Decime la nota " ,i, ":"
// 		Leer nota
		
// 		notas[i] <- nota
		
// 	FinPara
	
// 	Escribir nombre_alumno, notas[1]
	
// FinFuncion

// Funcion ver_promedio_general
// 	Escribir "Esta función aún está en construcción"
// FinFuncion


	